version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         docker build -t "masahitojp/frontend-base:$CIRCLE_BRANCH" .
         docker run "masahitojp/frontend-base:$CIRCLE_BRANCH"
